### PR TITLE
WIP: Adding Isolation Module

### PR DESCRIPTION
**Pull request by zhenbinwu**
A basic isolation module following Luca's HLS code: https://github.com/l-cadamuro/MuL1HLSFW/tree/master/MuonAlgorithms/Isolation

The data format of TrackerMuon and ConvertedTracks are still pending. Once we reach agreement, 
we should have better descriptions of these two classes between emulator and firmware.

### CODE REVIEW

**Comment by bachtis** [comment]
@zhenbinwu Can you do a git pull and update it  . I uploaded stuff yesterday and seems it conflicts but the resolve should be trivial

**Comment by zhenbinwu** [comment]
Ok, done.

I think the test.py is not updated in your branch. I will wrap up the isolation config later.

**Comment by bachtis** [comment]
@zhenbinwu 
OK merged.
One thing: I saw you padded zeros for muons but I am sure you can replicate the algorithm firmware without doing that saving CPU time. Worth checking ..
 M

**Comment by zhenbinwu** [comment]
Oh, we can remove that. I padded empty muons for testing dump.

**Pull request merged**
